# -- Temporary exports
#
# Other login files (e.g., .aliases) are platform specific, so we try to
# determine the platform we're operating on upon login and then export it so
# that other login scripts are aware and can act accordingly.
if command -v uname >/dev/null; then
  platform="$(uname -s)"
  if [[ "${platform}" == "Linux" || "${platform}" == "Darwin" ]]; then
    export platform
  fi
fi

# -- Exports for interactive shells
#
# The coreutils package on Ubuntu 20.04 has started wrapping strings in its
# output with single quotes (') for reasons that are completely beyond me. Fix
# this behavior in interactive shells and set the quoting style to be literal.
# Yet another reason to never parse the output of the 'ls' command
export QUOTING_STYLE=literal

# Rather than overwriting the history file (which is the default behavior for
# some reason), append to it instead.
shopt -s histappend

export HISTSIZE=1000
export HISTFILESIZE=10000

# -- Aliases
if [[ -f "${HOME}/.aliases" ]]; then
  source "${HOME}/.aliases"
fi

# -- Set prompt command
if [[ -f "${HOME}/.prompt" ]]; then
  source "${HOME}/.prompt"
fi

# -- Less needs some configuration to be useful
export LESS=" -R -X -I"

# -- List Directory Colors
if [[ -x /usr/bin/dircolors ]]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# Get rid of the scourge that is programmable completion
complete -r

# -- Do not export these to the login environments
unset platform

# -- Readline customizations
#
# Ring the bell silently
bind 'set bell-style visible'
# Symlinked directories get a trailing slash after TAB completion
bind 'set mark-symlinked-directories on'
