if [[ -f "${HOME}/.profile" ]]; then
  source "${HOME}/.profile"
fi

# For all other items that are set for interactive, non-login shells we look to
# .bashrc instead.  Note that on OS X, the Terminal app runs a login shell for
# every tab or window that is opened
if [[ -f "${HOME}/.bashrc" ]]; then
  source "${HOME}/.bashrc"
fi

# If homebrew is installed, then we set some stuff for that too
if [[ -x "/opt/homebrew/bin/brew" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
